### ISSUE TITLE
[System unit] copy() doesn't work on dynamic array

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#11]
As issue #10 that I just reported, another issue I found is Pascal N-IDE's `copy()` function doesn't work on dynamic array. It only works on string, as shown by auto-completion hint/info. I think it's a miss on your part, I suppose.

Actually, in _modern_ Pascal, `copy()` works both on string and dynamic array. As it does on Free Pascal, Delphi, or other modern Pascal compilers. I think you should upgrade your interpreter abilities so it's compatible with other Pascal compilers being widely used today.

Reference:
- https://www.freepascal.org/docs-html/rtl/system/copy.html
- http://www.delphibasics.co.uk/RTL.asp?Name=copy

**Comment by tranleduy2000** [comment]
I added copy function in https://github.com/tranleduy2000/pascalnide/commit/d294953e75c0a646983532e11b94a303ff0f4485
