### ISSUE TITLE
[Graph unit] Different font face for each text style

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#12]
In **Graph** unit, `setTextStyle()` function provide at least 7 kinds of font face. But, as I play around with Graph unit, it seems that only available 2 font faces provided by Pascal N-IDE. One for `sansSerifFont` and one for the others. So, could you please give each of them different font face?

Here's my suggestion:
- `TriplexFont`: Tahoma, Verdana
- `SmallFont`: Palatino Linotype
- `SansSerifFont`: Arial, Helvetica
- `GothicFont`: Times New Roman, Georgia
- `ScriptFont`: Comic Sans MS
- `TSCRFont`: Courier New, Lucida Console
- `BoldFont`: Impact, Arial Black

Or simply pick any suitable fonts provided by Google.

Reference:
- `setTextStyle()`:  https://www.freepascal.org/docs-html/rtl/graph/settextstyle.html
- Google fonts: https://www.w3schools.com/howto/howto_google_fonts.asp
- web fonts: https://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by tranleduy2000** [comment]
All fonts must be fixed width. Thank you for your suggest.

**Comment by pakLebah** [comment]
Why all the fonts must be fixed width? It's for graph unit, not for the editor nor the console. We should be able to use any kind of fonts on graph mode, right?

**Comment by tranleduy2000** [comment]
We can use any font.
But when drawing I need to calculate the exact size of the characters. The fixed width font is a great choice for performance. But if you want, I can adding the fonts, it looks great.

**Comment by tranleduy2000** [comment]
Added in the commit 973af72302bc8b130b1885c13e8b2dd55fb6edce

**Comment by pakLebah** [comment]
You may keep the performance on fixed-width fonts. But provide other fonts as option so we could pick that if we really need to.
