### ISSUE TITLE
[IDE console] How to change output console font?

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#13]
I'm looking for a way to change output console's font face and size, because sometimes I want my program to be able to use larger font. It seems that it's not customizable yet, am I right? I suggest you to use monospace fonts for output console like Courier New or Lucida Console or Menlo or something like that.

**Comment by tranleduy2000** [comment]
Change font console is premium feature. I will add the feature change font size of console in the settings.

**Comment by tranleduy2000** [comment]
You can uses graph unit.
