### ISSUE TITLE
[Editor] Set default indent to 2 spaces

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#15]
Due to smartphone screen size limit, I suggest the app to set editor's default indentation to 2 spaces. Apply it to the code formatter/beautifier as well. Pascal is a verbose language, 2 spaces indentation is clear enough. And please don't use tabs for indentation because it's not portable for copy-and-paste operation across apps/editors.

**Comment by tranleduy2000** [comment]
2 space has default in v4.0.3
