### ISSUE TITLE
wrong version number in 4.0.4 APK

### ISSUE THREAD

**Issue by IzzySoft** [tranleduy2000/pascalnide#16]
Just a note: looks like you forgot to increase `versionName` and `versionCode` with the latest release:

    package: name='com.duy.pascal.compiler' versionCode='103' versionName='4.0.3' platformBuildVersionName='7.1.1'

**Comment by tranleduy2000** [comment]
Fixed in 4cb00b9e71cd99ef269ba2fb406dbf1875e29ce1
