### ISSUE TITLE
False error in a recursive function

### ISSUE THREAD

**Issue by nikelsad** [tranleduy2000/pascalnide#22]
I've got an error in a recursive function in a place where it should get itself a value that it should return. The error states about wrong number of arguments. But to give a value to a function one should assign it to the name of the funct. without any arguments. On a desktop this code works as it should.
```pascal
function fib(n: Integer): Integer;
var f:Integer;
begin
  if n < 1 then fib:= fib(n+2)-fib(n+1)
    else if n > 2 then fib:= fib(n-2) + fib(n-1)
      else fib:=1;
end;
```

**Comment by tranleduy2000** [comment]
Thanks for report bug.

**Comment by tranleduy2000** [comment]
Fixed in latest commit
