### ISSUE TITLE
Error of compile

### ISSUE THREAD

**Issue by SashaKar1** [tranleduy2000/pascalnide#23]
![screenshot_2017-12-01-01-01-18](https://user-images.githubusercontent.com/34140055/33449862-41ad3024-d634-11e7-9d57-da8668531f79.png)
![screenshot_2017-12-01-01-01-22](https://user-images.githubusercontent.com/34140055/33449895-4aa89b6e-d634-11e7-89fc-0df4ad837af6.png)

**Comment by tranleduy2000** [comment]
Hello, you can't print the array.
Please uses this code
```pascal
for i := 1 to 7 do write(mas[i]);
```
