### ISSUE TITLE
[SysUtils unit] Format function is missing

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#6]
In **SysUtils** unit, the `format()` function is missing. It's to use string formatting with formatting symbols. The symbols are similar to C's string formatting.

Example:
```pascal
writeln(format('%s = %d',['text',123]));
```

Reference: https://www.freepascal.org/docs-html/rtl/sysutils/format.html

**Comment by tranleduy2000** [comment]
Format function is supported in v4.0.1  https://github.com/tranleduy2000/pascalnide/releases/tag/v4.0.1
See commit https://github.com/tranleduy2000/pascalnide/commit/75a361ecb36ac6dab9eb2ac211a65e0203680f03

Reference https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html
