### ISSUE TITLE
[lang] Function result variabel doesn't work

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#8]
Today's Pascal —as being used by FPC and Delphi since ages ago— has `result` variable declared implicitly within a function. This doesn't work in Pascal N-IDE.

Example:
```pascal
function f(p: integer): string;
// var result: string <-- implicitly added by the compiler
begin
  if p = 0 then
    result := 'zero'
  else
    result := intToStr(p);
end;
```

Because `result` is a variable, it _acts_ like a variable. For example, if the function output is a dynamic array, the `result` size can be defined by `setLength()` procedure from within the function.

Reference: https://www.freepascal.org/docs-html/current/ref/refse90.html#x174-19600014.3

**Comment by tranleduy2000** [comment]
I supported ``result`` variable, add ``{$MODE DELPHI}`` in the top of program.
See commit 337d56184f8bd675542d500ffc8be9197b551dbc
