### ISSUE TITLE
[Graph unit] Color transparency isn't supported

### ISSUE THREAD

**Issue by pakLebah** [tranleduy2000/pascalnide#9]
**Graph** unit is an old unit, legacy of Turbo Pascal. But as N-IDE is created in today modern world, it should work with modern technology as well, including in color values. Current **Graph** unit doesn't provide support to define color transparency (alpha) value in any ways. Hopefully it will be supported in the future version.

**Comment by tranleduy2000** [comment]
ARGB is supported in v4.0.0
https://github.com/tranleduy2000/pascalnide/releases/tag/v4.0.0

**Comment by pakLebah** [comment]
How to use color with transparency? For example with `setColor()` in graph unit or `textColor()` in CRT unit. The color selector also doesn't have transparency setting.

**Comment by tranleduy2000** [comment]
I missing set up alpha mod, I fixed this bug.
See sample https://github.com/tranleduy2000/pascalnide/commit/235b68c2e79914d589bf766e328a49754b5adba9#diff-c7e640003012c86a1867e09c011a7873
and 
https://github.com/tranleduy2000/pascalnide/commit/235b68c2e79914d589bf766e328a49754b5adba9#diff-d93e1405983543083416ca680c4be4e7
![screenshot_20170617-153243](https://user-images.githubusercontent.com/19369448/27251550-6396c2f2-5373-11e7-8f10-319bfcb7f8bc.png)
![screenshot_20170617-154052](https://user-images.githubusercontent.com/19369448/27251551-639d6f9e-5373-11e7-83eb-b457101e7468.png)

Apk release https://github.com/tranleduy2000/pascalnide/releases/tag/v4.0.2
